### ISSUE TITLE
Build fails with bytes 0.5.0

### ISSUE THREAD

**Issue by abbec** [danburkert/prost#242]
When building with bytes 0.5 I get these errors:

```
error[E0276]: impl has stricter requirements than trait
 --> src/protos/owl.rs:8:28
  |
8 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                            ^^^^^^^^^^^^^^^^ impl has extra requirement `B: protos::owl::HelloRequest_MESSAGE::_bytes::Buf`

error[E0277]: the trait bound `B: bytes::buf::buf_mut::BufMut` is not satisfied
   --> src/protos/owl.rs:2:28
    |
2   | #[derive(Clone, PartialEq, ::prost::Message)]
    |                            ^^^^^^^^^^^^^^^^ the trait `bytes::buf::buf_mut::BufMut` is not implemented for `B`
    |
   ::: /mnt/home/albert.cervin/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-0.5.0/src/encoding.rs:704:12
    |
704 |         B: BufMut,
    |            ------ required by this bound in `protos::owl::HelloRequest_MESSAGE::_prost::encoding::string::encode`
    |
    = help: consider adding a `where B: bytes::buf::buf_mut::BufMut` bound
```

**Comment by LucioFranco** [comment]
This is because prost requires the 0.4 trait and you are including the 0.5 trait for the macro.

**Comment by dingelish** [comment]
Hi @LucioFranco , I'm encountering the same problem. Somehow I managed to make prost work with bytes 0.5, and `cargo test` passed. But I cannot make the "tests" pass. Could I have some advise from you? Thanks! My commit is:

https://github.com/danburkert/prost/compare/master...dingelish:master

**Comment by hadronzoo** [comment]
I'm running into the same issue as Tokio 0.2 requires bytes ^0.5.0.

**Comment by dingelish** [comment]
Hi @LucioFranco , my fork can pass all of the tests now. Basically,

- Replaced all `IntoBuf` with `Buf`
- Construct a `Bytes` structure for each `IntoBuf` generated ones.
- Fixes all tests.

@hadronzoo  @abbec Could you please test my fork? Thanks!

https://github.com/dingelish/prost

**Comment by hntd187** [comment]
@dingelish you should put in a PR here to merge into the next version

**Comment by jasonlor** [comment]
+1 also seeing this issue.

**Comment by Ciantic** [comment]
0.5 merge [was merged in the master](https://github.com/danburkert/prost/pull/251), but it's not released. If you are "seeing this issue", are you using the released version (outdated) or master from this repo?

I think the 0.5 support should be released if it's working in the master. I'm also waiting because I'd like to use tonic, which is also waiting release.

**Comment by danburkert** [comment]
This should be fixed as of `prost` 0.6.0.  If you still have issues after updating please reopen.
