### ISSUE TITLE
Failures when building with rust 2018

### ISSUE THREAD

**Issue by SecurityInsanity** [danburkert/prost#140]
Enabling rust 2018 on a prost project will cause failures in certain generated messages. Specifically, those generated messages who end up generating modules. Specifically you might see error messages like:

```
error: cannot find derive macro `Oneof` in this scope
  --> /Users/vagrant/git/target/debug/build/gwiz-rust-427dfcfefeb48ff9/out/grpc.slack.rs:82:21
   |
82 |     #[derive(Clone, Oneof, PartialEq)]
   |                     ^^^^^
```

Or maybe even some messages like:

```
error[E0658]: The attribute `prost` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /Users/vagrant/git/target/debug/build/gwiz-rust-427dfcfefeb48ff9/out/grpc.slack.rs:90:9
   |
90 |         #[prost(string, tag="4")]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^
```

These are caused by internal modules not including the types from: `prost_derive`. (Specifically the generated macro types).

All we _should_ need is an: "use prost_derive::*" in these generated modules, however we probably want to also turn it into a feature for only 2018, so this crate doesn't force 2018 edition code on others. Or maybe since it's an include that just won't get used it's fine since it'll be optimized away?

**Comment by vorner** [comment]
I've worked around this with:

```rust
mod proto {
    use prost_derive::{Enumeration, Message};
    include!(concat!(env!("OUT_DIR"), "/proto.rs"));
}

**Comment by danburkert** [comment]
This should be fixed as of 0.5.0.  Please re-open if that's not the case.

**Comment by kathampy** [comment]
@danburkert actix-protobuf doesn't seem to work with prost 0.5.0. Maybe a 0.4.1 release with a fix is warranted.

**Comment by kathampy** [comment]
> @kathampy there will not be bugfix releases on previous minor release branches of `prost` in the foreseeable future, I just don't have the time to do so. As it is `prost` already badly needs a 0.6 release, and I haven't had time to wrap up the things necessary to do it.
The `use prost_derive::*` workaround is fine when using `prost 0.4.0`.

> Separately, I don't see how that linked actix ticket relates to this issue. More details are needed.
You cannot use actix-protobuf with `prost-build 0.4.0` without the above workound, and it seems incompatible with `prost 0.5.0`.
